# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ata < Formula
  desc "Ask the Terminal Anything — chat with Claude from your terminal"
  homepage "https://github.com/alexraskin/ata"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.8/ata_0.1.8_darwin_amd64.tar.gz"
      sha256 "a1876b1969bb04b70a11bc8cecebee49c655f968bd648619330b41e2edc0f21a"

      define_method(:install) do
        bin.install "ata"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.8/ata_0.1.8_darwin_arm64.tar.gz"
      sha256 "5dcf8531f029d6f14f01fe3d064474ee8a3c063603370a4e89dbda8564b65302"

      define_method(:install) do
        bin.install "ata"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.8/ata_0.1.8_linux_amd64.tar.gz"
      sha256 "641dfb9bc3870794bbf7e12b775040a129320412bd10fb5f39a97ea81112cc24"
      define_method(:install) do
        bin.install "ata"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.8/ata_0.1.8_linux_arm64.tar.gz"
      sha256 "6c61eaba2fd36281e62a0cebd273511d8ace39cd56d2b2fb38b3e3308d6d5b09"
      define_method(:install) do
        bin.install "ata"
      end
    end
  end

  def post_install
    system "xattr", "-cr", "#{bin}/ata"
  end
end
