# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc "Simple CLI to format todos"
  homepage "https://github.com/alexraskin/todo-cli"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexraskin/todo-cli/releases/download/v0.1.3/todo-cli_0.1.3_darwin_amd64.tar.gz"
      sha256 "f8957c61d42dc065ea13148d0273f747aeea22e015cd374e6bc9b1d513dfd905"

      define_method(:install) do
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexraskin/todo-cli/releases/download/v0.1.3/todo-cli_0.1.3_darwin_arm64.tar.gz"
      sha256 "25876776eae0194465eb69cbd5d99899058cd8845101d096d242901536e18afa"

      define_method(:install) do
        bin.install "todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexraskin/todo-cli/releases/download/v0.1.3/todo-cli_0.1.3_linux_amd64.tar.gz"
      sha256 "c6513dc463cb1a6d1811669d9efd154cd9ba55f8a2d94c974d474376b068bd78"
      define_method(:install) do
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexraskin/todo-cli/releases/download/v0.1.3/todo-cli_0.1.3_linux_arm64.tar.gz"
      sha256 "bb0b07d198c4ff8f42d5bf3ab750978bd4361ca71ab7f513e74c61d20c4409ce"
      define_method(:install) do
        bin.install "todo"
      end
    end
  end
end
