# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc "Simple CLI to format todos"
  homepage "https://github.com/alexraskin/todo-cli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexraskin/todo-cli/releases/download/v0.1.2/todo-cli_0.1.2_darwin_amd64.tar.gz"
      sha256 "44358fe52ad56c9339caa94d444d1affa434ded8525a26902094bd48c15cf10d"

      define_method(:install) do
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexraskin/todo-cli/releases/download/v0.1.2/todo-cli_0.1.2_darwin_arm64.tar.gz"
      sha256 "1b7ef8406fbc38bf5a2ff216e91967e418090b99a659698afabf775e08143be2"

      define_method(:install) do
        bin.install "todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexraskin/todo-cli/releases/download/v0.1.2/todo-cli_0.1.2_linux_amd64.tar.gz"
      sha256 "8e44e0a99d6706ba9e8adf16c4fbf838659833fbe1352f1fc5c6be0d1769c195"
      define_method(:install) do
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexraskin/todo-cli/releases/download/v0.1.2/todo-cli_0.1.2_linux_arm64.tar.gz"
      sha256 "bd533556eecc814664fe69b425ecdaa88067dfe2c261f8bcb8c155b432853013"
      define_method(:install) do
        bin.install "todo"
      end
    end
  end
end
