# This file was generated by GoReleaser. DO NOT EDIT.
cask "ata" do
  name "ata"
  desc "Ask the Terminal Anything — chat with Claude from your terminal"
  homepage "https://github.com/alexraskin/ata"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ata"

  on_macos do
    on_intel do
      url "https://github.com/alexraskin/ata/releases/download/v#{version}/ata_#{version}_darwin_amd64.tar.gz"
      sha256 "449a3df6ca199f812675697c164a0ae7a97a66035b568f6d31da0bfc0eb6a1d4"
    end
    on_arm do
      url "https://github.com/alexraskin/ata/releases/download/v#{version}/ata_#{version}_darwin_arm64.tar.gz"
      sha256 "e760368fc0213b1d991ad6110509fb843eda275148911124b7f3cf40e4739b42"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexraskin/ata/releases/download/v#{version}/ata_#{version}_linux_amd64.tar.gz"
      sha256 "a112905df7220b02cbc37b4a7f18816167f02e9ab88fcceb7d5c1e44218197c7"
    end
    on_arm do
      url "https://github.com/alexraskin/ata/releases/download/v#{version}/ata_#{version}_linux_arm64.tar.gz"
      sha256 "cec8a8ad7fa53462394993595a5213bab337d904d7db323ac633818142863657"
    end
  end

  # No zap stanza required
end
