# This file was generated by GoReleaser. DO NOT EDIT.
cask "ata" do
  name "ata"
  desc "Ask the Terminal Anything — chat with Claude from your terminal"
  homepage "https://github.com/alexraskin/ata"
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ata"

  on_macos do
    on_intel do
      url "https://github.com/alexraskin/ata/releases/download/v#{version}/ata_#{version}_darwin_amd64.tar.gz"
      sha256 "c121d393566c94bc7dd15ad3002808794f1b6fc6f99e4a79f13c3a526c48f34d"
    end
    on_arm do
      url "https://github.com/alexraskin/ata/releases/download/v#{version}/ata_#{version}_darwin_arm64.tar.gz"
      sha256 "b5c26a528c5d1a3fa531bfc14597698270644ed627122ebcfc944e7d37b0be54"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexraskin/ata/releases/download/v#{version}/ata_#{version}_linux_amd64.tar.gz"
      sha256 "dfc7a93a990847cc3c67b88d2e919440a667985955abd2b7aa1c88d2f6d8b7f9"
    end
    on_arm do
      url "https://github.com/alexraskin/ata/releases/download/v#{version}/ata_#{version}_linux_arm64.tar.gz"
      sha256 "a3eab6c408ef6fdffa5f889befc17351c0b955c28def3952f76effeb06407f49"
    end
  end

  # No zap stanza required
end
