# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ata < Formula
  desc "Ask the Terminal Anything — chat with Claude from your terminal"
  homepage "https://github.com/alexraskin/ata"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.9/ata_0.1.9_darwin_amd64.tar.gz"
      sha256 "835ca9c6e30cd5f1ac7d52719853a5277bf62264e60cb2abb751273babe44343"

      define_method(:install) do
        bin.install "ata"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.9/ata_0.1.9_darwin_arm64.tar.gz"
      sha256 "c680dfc4fb776ee93a623c3f0adfd6f2455cc02a8fa95fd880b63373dfd5725f"

      define_method(:install) do
        bin.install "ata"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.9/ata_0.1.9_linux_amd64.tar.gz"
      sha256 "0f9185e8fdaeeb442aedacf6644fccfd45e5399289277f54fbb2e63bfe0c2b79"
      define_method(:install) do
        bin.install "ata"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.9/ata_0.1.9_linux_arm64.tar.gz"
      sha256 "64d420939fc8a34024fc8ffa8471e9b53d2bd396bec7d9f76e471383a77c7768"
      define_method(:install) do
        bin.install "ata"
      end
    end
  end

  def post_install
    system "xattr", "-cr", "#{bin}/ata"
  end
end
