# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ata < Formula
  desc "Ask the Terminal Anything — chat with Claude from your terminal"
  homepage "https://github.com/alexraskin/ata"
  version "0.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.11/ata_0.1.11_darwin_amd64.tar.gz"
      sha256 "b65584259c5c491f1c588777e3e0f005cbc99885de4b54ef4cb2e6f24e7523e4"

      define_method(:install) do
        if OS.mac?
          system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "ata"
        end
        bin.install "ata"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.11/ata_0.1.11_darwin_arm64.tar.gz"
      sha256 "9f888db27b569aa7e1804ae2010664b682de26e4f38fa9383e5aa55a59f32537"

      define_method(:install) do
        if OS.mac?
          system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "ata"
        end
        bin.install "ata"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.11/ata_0.1.11_linux_amd64.tar.gz"
      sha256 "10d60fa950295aff65e9b64c1596cd4a9b930c9ce67f6d46fe08a51520d4a944"
      define_method(:install) do
        if OS.mac?
          system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "ata"
        end
        bin.install "ata"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexraskin/ata/releases/download/v0.1.11/ata_0.1.11_linux_arm64.tar.gz"
      sha256 "6c012bd38a49360cf41f5b38c9358de204874a80969c0b8c6fd09376ed6a9c1c"
      define_method(:install) do
        if OS.mac?
          system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "ata"
        end
        bin.install "ata"
      end
    end
  end
end
